### ISSUE TITLE
11/1: TODO List

### ISSUE THREAD

**Issue by niharmitra** [ucladevx/UCLAEats-backend#13]
Breaking bugs:
- [x] Rate Limit - stop the scraper from getting rate limited. 1) Get around the IP blocker 2) use sleeps to space out requests 3) Cache nutrition data (which changes less often than the menus)
- [x] Messaging - various fixes, e.g. authentication for chatrooms, push notifications, make it stable

Improvements:
- [x] Review all authentication: make sure all APIs that are public are appropriately authenticated
- [ ] Improve the matching algorithm, e.g. Gale-Shapley like BruinMeet

Architecture Enhancements:
- [x] Merge the databases (all the Postgres databases under one container)
- [ ] Move the databases to AWS managed ones (from Docker container on EC2 to AWS RDS)

Future Improvements and Additions
- [ ] Update API endpoints to better reflect frontend usage and reduce necessary parsing (spec will come later)
- [ ] Scrape take-out menus
- [ ] Change email based API to use user id instead
